CREATE FUNCTION input(input VARCHAR(20)) RETURNS INT
BEGIN
DECLARE nm2 VARCHAR(20);
DECLARE i INT;
DECLARE j INT;
DECLARE count INT;
SET i = 1;
SET j = 1;
SET count = LENGTH(input);
		IF ASCII(nm2) >= ASCII('a') AND ASCII(nm2) <= ASCII('z')
		THEN
			SET nm2 = REPLACE(nm2, CHAR(ASCII(SUBSTRING(nm2,3,count))), CHAR(ASCII(SUBSTRING(nm2,3,count))-32));
		END IF;
RETURN nm2;
END&&